#!/usr/bin/env bash
# get the information about a specific subdomain for our website.

if [ $# -eq 2 ]; then
  subdomain=$2
else
  subdomain="www lb-01 web-01 web-02"
fi

# loop through each subdomain and display its DNS record
for sub in $subdomain; do
  record=$(dig +short $sub.$1)
  if [ -n "$record" ]; then
    echo "The subdomain $sub is an A record and points to $record"
  else
    echo "The subdomain $sub does not have a DNS record"
  fi
done
